# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49ca89a89a511765b8985ed99f5f58a791fbcd50f2db1f74b74cec44e108bb5b4e2a4439677fb1ea7b70fa03ae9f83048f26895ad16fb517ca5aa56b99cb4500

test:
  secret_key_base: a2770be31c09330fde1deb209bd814dfb6e2af1614994f168da215c66d65d6245c44f3ce7a9d75f0cb452458aab868699cbb5018a8f03af28f93d9a6fdd2232f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
